################################# Default configuration ###################
baseURL = "https://rbiologos.github.io"
title = "R Biólogos"
theme = "meghna-hugo"
#themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### Navegación en español ########################
[[Languages.en.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 1

[[Languages.en.menu.main]]
name = "Equipo"
pre = "#"
url = "team"
weight = 2

[[Languages.en.menu.main]]
name = "¿Qué somos?"
pre = "#"
url = "about"
weight = 3

[[Languages.en.menu.main]]
name = "¿Qué hacemos?"
pre = "#"
url = "feature"
weight = 4

[[Languages.en.menu.main]]
name = "Tienda"
pre = "#"
url = "portfolio"
weight = 5

[[Languages.en.menu.main]]
name = "Contacto"
pre = "#"
url = "contact"
weight = 6

################### English Navigation ########################
[[Languages.fr.menu.main]]
name = "Blog"
pre = "#"
url = "blog"
weight = 1

[[Languages.fr.menu.main]]
name = "Team"
pre = "#"
url = "team"
weight = 2


[[Languages.fr.menu.main]]
name = "About us"
pre = "#"
url = "about"
weight = 3

[[Languages.fr.menu.main]]
name = "Why?"
pre = "#"
url = "feature"
weight = 4

[[Languages.fr.menu.main]]
name = "Portfolio"
pre = "#"
url = "portfolio"
weight = 5

[[Languages.fr.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 6


############################# Default Parameters ##########################
[params]
logo = "https://i.ibb.co/FxCR4MP/loader.gif"
# Meta data
description = "El espacio perfecto para Biólogos y R"
author = "R Biólogos"
# Google Analytics
google_analytics_id = "G-N49JEEK9KF" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "https://i.ibb.co/FxCR4MP/loader.gif"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/rbiologiacol/"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/RBiologos/Posts"


################################ English Language ########################
[Languages.en]
languageName = "ES"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 Diseñado por [David Vanegas](https://github.com/davidvaneal) bajo la plantilla [Themefisher](https://themefisher.com) de [HUGO](https://gethugothemes.com)"

################################ France Language ########################
[Languages.fr]
languageName = "EN"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "Copyright &copy; 2020 Designed by [David Vanegas](https://github.com/davidvaneal) from [Themefisher](https://themefisher.com) to [HUGO](https://gethugothemes.com)"